### ISSUE TITLE
No module named 'smm_dijkstra'

### ISSUE THREAD

**Issue by XiaYifan1999** [paul0noah/spider-match#2]
run 'python spidermatch_example.py' 
exits:
ModuleNotFoundError: No module named 'smm_dijkstra'

Before, when we run 'python setup.py install'
we obtain  pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '7.5.0-6ubuntu2)'

When we try to pip install smm_dijkstra, Error: No matching distribution found for smm_dijkstra.

What's the problem, please?

**Comment by paul0noah** [comment]
I think you did not follow the installation instructions in the readme. Please do so and come back if the issue still exists.

**Comment by paul0noah** [comment]
Did you resolve the issue?

**Comment by XiaYifan1999** [comment]
It has to do with the version of gcc on the server, and it's possible to run it after an upgrade
