### ISSUE TITLE
"git clone git@github.com:paul0noah/spider-matchs.git" is denied access by the system

### ISSUE THREAD

**Issue by Dingmin-LI** [paul0noah/spider-match#3]
Hi, I'm using this code "git clone git@github.com:paul0noah/spider-matchs.git" to configure my environment and it's refusing to fetch it, how do I fix it?
![1720859099571](https://github.com/user-attachments/assets/77164673-26df-429a-ad67-e889dc9ad42c)

**Comment by paul0noah** [comment]
You have a typo. The repo is called `spider-match` and not `spider-matchs`. for further installation details please follow the readme :)
