### ISSUE TITLE
Small bug with using dataset option "smal"

### ISSUE THREAD

**Issue by tdvc** [paul0noah/spider-match#7]
Hi, it seems like there is a small bug when using the dataset option "smal" in spidermatch_example.py. The bug appers to occur, when loading a checkpoint from a trained model :)

**Comment by paul0noah** [comment]
Adding error from private chat with @tdvc 
```
Size([128, 3]) from checkpoint, the shape in current model is torch.Size([128, 128]).
```

**Comment by paul0noah** [comment]
@tdvc can you please check if the change fixes your bug?

**Comment by tdvc** [comment]
Yes, that solved the bug. Thank you very much :)
